apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deployapp
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployapp
