apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: cert-volume
          secret:
            secretName: "secret-nginx-cert"
      containers:
      - name: nginx
        image: huyhv/swarmtest:nginx
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - mountPath: "/certs" 
            name: cert-volume
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP 
    name: http
    nodePort: 31080
  - port: 443
    targetPort: 443
    protocol: TCP 
    name: https
    nodePort: 31443
